// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Core.Domain.Entities.Cms.CmsCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("BuiltIn")
                        .HasColumnType("boolean");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<bool>("IsPublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ParentCategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("PictureUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("CmsCategories", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Entities.Cms.CmsComment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AuthorEmail")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("BuiltIn")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("CmsNewsItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CmsPageId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsApproved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ParentCommentId")
                        .HasColumnType("uuid");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("integer");

                    b.Property<Guid?>("ShopProductId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CmsNewsItemId");

                    b.HasIndex("CmsPageId");

                    b.HasIndex("ParentCommentId");

                    b.HasIndex("ShopProductId");

                    b.ToTable("CmsComments", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Entities.Cms.CmsMenu", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("BuiltIn")
                        .HasColumnType("boolean");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("CmsMenus", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Entities.Cms.CmsMenuItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("BuiltIn")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("CmsMenuId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CmsPageId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CssClass")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("IconClass")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsPublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("OpenInNewWindow")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("Order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<Guid?>("ParentMenuItemId")
                        .HasColumnType("uuid");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Url")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("CmsMenuId");

                    b.HasIndex("CmsPageId");

                    b.HasIndex("ParentMenuItemId");

                    b.ToTable("CmsMenuItems", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Entities.Cms.CmsNewsItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .HasColumnType("text");

                    b.Property<bool>("BuiltIn")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("CmsCategoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CmsPhotoGalleryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<bool>("IsPublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Keywords")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("PictureUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("integer");

                    b.Property<bool>("ShowComments")
                        .HasColumnType("boolean");

                    b.Property<string>("Tags")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("CmsCategoryId");

                    b.HasIndex("CmsPhotoGalleryId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("CmsNewsItems", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Entities.Cms.CmsPage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .HasColumnType("text");

                    b.Property<bool>("BuiltIn")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("CmsCategoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CmsPhotoGalleryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<bool>("IsFrontPage")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Keywords")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("MasterPage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("PictureUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("integer");

                    b.Property<bool>("ShowBreadcrumbs")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("ShowComments")
                        .HasColumnType("boolean");

                    b.Property<string>("Tags")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("CmsCategoryId");

                    b.HasIndex("CmsPhotoGalleryId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("CmsPages", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Entities.Cms.CmsPhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("BuiltIn")
                        .HasColumnType("boolean");

                    b.Property<Guid>("CmsPhotoGalleryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("integer");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Title")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("CmsPhotoGalleryId");

                    b.ToTable("CmsPhotos", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Entities.Cms.CmsPhotoGallery", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("BuiltIn")
                        .HasColumnType("boolean");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("CoverImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<bool>("IsPublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("CmsPhotoGalleries", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Entities.Constructor.ConstructorOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("BuiltIn")
                        .HasColumnType("boolean");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerEmail")
                        .HasColumnType("text");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerPhone")
                        .HasColumnType("text");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RowVersion")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("TotalPrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("ConstructorOrders");
                });

            modelBuilder.Entity("Core.Domain.Entities.Constructor.ConstructorStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("BuiltIn")
                        .HasColumnType("boolean");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("RowVersion")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ConstructorSteps");
                });

            modelBuilder.Entity("Core.Domain.Entities.Constructor.ConstructorStepProperty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("BuiltIn")
                        .HasColumnType("boolean");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ConstructorStepId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ConstructorStepPropertyGroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ConstructorStepPropertyTypeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("RowVersion")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ConstructorStepId");

                    b.HasIndex("ConstructorStepPropertyGroupId");

                    b.HasIndex("ConstructorStepPropertyTypeId");

                    b.ToTable("ConstructorStepProperties");
                });

            modelBuilder.Entity("Core.Domain.Entities.Constructor.ConstructorStepPropertyAvailableValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("BuiltIn")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ConstructorStepPropertyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<decimal?>("PriceModifier")
                        .HasColumnType("numeric");

                    b.Property<int>("RowVersion")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ConstructorStepPropertyId");

                    b.ToTable("ConstructorStepPropertyAvailableValues");
                });

            modelBuilder.Entity("Core.Domain.Entities.Constructor.ConstructorStepPropertyGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("BuiltIn")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("RowVersion")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ConstructorStepPropertyGroups");
                });

            modelBuilder.Entity("Core.Domain.Entities.Constructor.ConstructorStepPropertyType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("BuiltIn")
                        .HasColumnType("boolean");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RowVersion")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ConstructorStepPropertyTypes");
                });

            modelBuilder.Entity("Core.Domain.Entities.Constructor.ConstructorStepPropertyValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("BuiltIn")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ConstructorOrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ConstructorStepPropertyAvailableValueId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConstructorStepPropertyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RowVersion")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ConstructorOrderId");

                    b.HasIndex("ConstructorStepPropertyAvailableValueId");

                    b.HasIndex("ConstructorStepPropertyId");

                    b.ToTable("ConstructorStepPropertyValues");
                });

            modelBuilder.Entity("Core.Domain.Entities.Shop.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("BuiltIn")
                        .HasColumnType("boolean");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ParentCategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("PictureUrl")
                        .HasColumnType("text");

                    b.Property<int>("RowVersion")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("ShopCategories");
                });

            modelBuilder.Entity("Core.Domain.Entities.Shop.ShopDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("BuiltIn")
                        .HasColumnType("boolean");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("Cost")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("EstimatedTime")
                        .HasColumnType("text");

                    b.Property<decimal?>("FreeFromAmount")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("RowVersion")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ShopDeliveries");
                });

            modelBuilder.Entity("Core.Domain.Entities.Shop.ShopDiscount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("BuiltIn")
                        .HasColumnType("boolean");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<decimal>("DiscountValue")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<int?>("MaxUsageCount")
                        .HasColumnType("integer");

                    b.Property<decimal?>("MinOrderAmount")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PromoCode")
                        .HasColumnType("text");

                    b.Property<int>("RowVersion")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ShopDiscountTypeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UsageCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ShopDiscountTypeId");

                    b.ToTable("ShopDiscounts");
                });

            modelBuilder.Entity("Core.Domain.Entities.Shop.ShopDiscountType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("BuiltIn")
                        .HasColumnType("boolean");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RowVersion")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ShopDiscountTypes");
                });

            modelBuilder.Entity("Core.Domain.Entities.Shop.ShopOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("BuiltIn")
                        .HasColumnType("boolean");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerEmail")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("CustomerPhone")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DeliveryAddress")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<decimal?>("DeliveryCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FinalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("integer");

                    b.Property<Guid?>("ShopDeliveryId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ShopDiscountId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ShopOrderStatusId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.HasIndex("ShopDeliveryId");

                    b.HasIndex("ShopDiscountId");

                    b.HasIndex("ShopOrderStatusId");

                    b.ToTable("ShopOrders", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Entities.Shop.ShopOrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("BuiltIn")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("DiscountAmount")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProductCode")
                        .HasColumnType("text");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<int>("RowVersion")
                        .HasColumnType("integer");

                    b.Property<Guid>("ShopOrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ShopProductId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ShopOrderId");

                    b.HasIndex("ShopProductId");

                    b.ToTable("ShopOrderItems");
                });

            modelBuilder.Entity("Core.Domain.Entities.Shop.ShopOrderItemOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("BuiltIn")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OptionName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OptionValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("PriceModifier")
                        .HasColumnType("numeric");

                    b.Property<int>("RowVersion")
                        .HasColumnType("integer");

                    b.Property<Guid>("ShopOrderItemId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ShopOrderItemId");

                    b.ToTable("ShopOrderItemOptions");
                });

            modelBuilder.Entity("Core.Domain.Entities.Shop.ShopOrderStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("BuiltIn")
                        .HasColumnType("boolean");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsFinal")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("RowVersion")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ShopOrderStatuses");
                });

            modelBuilder.Entity("Core.Domain.Entities.Shop.ShopPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<bool>("BuiltIn")
                        .HasColumnType("boolean");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RowVersion")
                        .HasColumnType("integer");

                    b.Property<Guid>("ShopOrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ShopPaymentTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TransactionId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ShopOrderId");

                    b.HasIndex("ShopPaymentTypeId");

                    b.ToTable("ShopPayments");
                });

            modelBuilder.Entity("Core.Domain.Entities.Shop.ShopPaymentType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("BuiltIn")
                        .HasColumnType("boolean");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RowVersion")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ShopPaymentTypes");
                });

            modelBuilder.Entity("Core.Domain.Entities.Shop.ShopProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Article")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Body")
                        .HasColumnType("text");

                    b.Property<bool>("BuiltIn")
                        .HasColumnType("boolean");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<decimal?>("Height")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsPublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("IssueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Keywords")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<decimal?>("Length")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal?>("OldPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("PictureUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("integer");

                    b.Property<Guid?>("ShopProductVendorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tags")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Url")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Width")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ShopProductVendorId");

                    b.ToTable("ShopProducts", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Entities.Shop.ShopProductCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("BuiltIn")
                        .HasColumnType("boolean");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("RowVersion")
                        .HasColumnType("integer");

                    b.Property<Guid>("ShopProductId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ShopProductId");

                    b.ToTable("ShopProductCategories");
                });

            modelBuilder.Entity("Core.Domain.Entities.Shop.ShopProductOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("BuiltIn")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("RowVersion")
                        .HasColumnType("integer");

                    b.Property<Guid>("ShopProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ShopProductId");

                    b.ToTable("ShopProductOptions");
                });

            modelBuilder.Entity("Core.Domain.Entities.Shop.ShopProductOptionItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("BuiltIn")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<decimal?>("PriceModifier")
                        .HasColumnType("numeric");

                    b.Property<int>("RowVersion")
                        .HasColumnType("integer");

                    b.Property<Guid>("ShopProductOptionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ShopProductOptionId");

                    b.ToTable("ShopProductOptionItems");
                });

            modelBuilder.Entity("Core.Domain.Entities.Shop.ShopProductPhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("BuiltIn")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("RowVersion")
                        .HasColumnType("integer");

                    b.Property<Guid>("ShopProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ShopProductId");

                    b.ToTable("ShopProductPhotos");
                });

            modelBuilder.Entity("Core.Domain.Entities.Shop.ShopProductProperty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("BuiltIn")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("RowVersion")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ShopProductPropertyGroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ShopProductPropertyGroupId");

                    b.ToTable("ShopProductProperties");
                });

            modelBuilder.Entity("Core.Domain.Entities.Shop.ShopProductPropertyGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("BuiltIn")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("RowVersion")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ShopProductPropertyGroups");
                });

            modelBuilder.Entity("Core.Domain.Entities.Shop.ShopProductPropertyValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("BuiltIn")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RowVersion")
                        .HasColumnType("integer");

                    b.Property<Guid>("ShopProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ShopProductPropertyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ShopProductId");

                    b.HasIndex("ShopProductPropertyId");

                    b.ToTable("ShopProductPropertyValues");
                });

            modelBuilder.Entity("Core.Domain.Entities.Shop.ShopProductVendor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("BuiltIn")
                        .HasColumnType("boolean");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RowVersion")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WebsiteUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ShopProductVendors");
                });

            modelBuilder.Entity("ShopProductShopProduct", b =>
                {
                    b.Property<Guid>("RelatedProductsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ShopProductId")
                        .HasColumnType("uuid");

                    b.HasKey("RelatedProductsId", "ShopProductId");

                    b.HasIndex("ShopProductId");

                    b.ToTable("ShopProductRelatedProducts", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Entities.Cms.CmsCategory", b =>
                {
                    b.HasOne("Core.Domain.Entities.Cms.CmsCategory", "ParentCategory")
                        .WithMany("ChildCategories")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("Core.Domain.Entities.Cms.CmsComment", b =>
                {
                    b.HasOne("Core.Domain.Entities.Cms.CmsNewsItem", "CmsNewsItem")
                        .WithMany("Comments")
                        .HasForeignKey("CmsNewsItemId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Core.Domain.Entities.Cms.CmsPage", "CmsPage")
                        .WithMany("Comments")
                        .HasForeignKey("CmsPageId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Core.Domain.Entities.Cms.CmsComment", "ParentComment")
                        .WithMany("Replies")
                        .HasForeignKey("ParentCommentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Core.Domain.Entities.Shop.ShopProduct", null)
                        .WithMany("Comments")
                        .HasForeignKey("ShopProductId");

                    b.Navigation("CmsNewsItem");

                    b.Navigation("CmsPage");

                    b.Navigation("ParentComment");
                });

            modelBuilder.Entity("Core.Domain.Entities.Cms.CmsMenuItem", b =>
                {
                    b.HasOne("Core.Domain.Entities.Cms.CmsMenu", "CmsMenu")
                        .WithMany("MenuItems")
                        .HasForeignKey("CmsMenuId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Core.Domain.Entities.Cms.CmsPage", "CmsPage")
                        .WithMany("MenuItems")
                        .HasForeignKey("CmsPageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Core.Domain.Entities.Cms.CmsMenuItem", "ParentMenuItem")
                        .WithMany("ChildMenuItems")
                        .HasForeignKey("ParentMenuItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CmsMenu");

                    b.Navigation("CmsPage");

                    b.Navigation("ParentMenuItem");
                });

            modelBuilder.Entity("Core.Domain.Entities.Cms.CmsNewsItem", b =>
                {
                    b.HasOne("Core.Domain.Entities.Cms.CmsCategory", "CmsCategory")
                        .WithMany("NewsItems")
                        .HasForeignKey("CmsCategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Core.Domain.Entities.Cms.CmsPhotoGallery", "CmsPhotoGallery")
                        .WithMany("NewsItems")
                        .HasForeignKey("CmsPhotoGalleryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CmsCategory");

                    b.Navigation("CmsPhotoGallery");
                });

            modelBuilder.Entity("Core.Domain.Entities.Cms.CmsPage", b =>
                {
                    b.HasOne("Core.Domain.Entities.Cms.CmsCategory", "CmsCategory")
                        .WithMany("Pages")
                        .HasForeignKey("CmsCategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Core.Domain.Entities.Cms.CmsPhotoGallery", "CmsPhotoGallery")
                        .WithMany("Pages")
                        .HasForeignKey("CmsPhotoGalleryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CmsCategory");

                    b.Navigation("CmsPhotoGallery");
                });

            modelBuilder.Entity("Core.Domain.Entities.Cms.CmsPhoto", b =>
                {
                    b.HasOne("Core.Domain.Entities.Cms.CmsPhotoGallery", "CmsPhotoGallery")
                        .WithMany("Photos")
                        .HasForeignKey("CmsPhotoGalleryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CmsPhotoGallery");
                });

            modelBuilder.Entity("Core.Domain.Entities.Constructor.ConstructorStepProperty", b =>
                {
                    b.HasOne("Core.Domain.Entities.Constructor.ConstructorStep", "ConstructorStep")
                        .WithMany("Properties")
                        .HasForeignKey("ConstructorStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Domain.Entities.Constructor.ConstructorStepPropertyGroup", "ConstructorStepPropertyGroup")
                        .WithMany("Properties")
                        .HasForeignKey("ConstructorStepPropertyGroupId");

                    b.HasOne("Core.Domain.Entities.Constructor.ConstructorStepPropertyType", "ConstructorStepPropertyType")
                        .WithMany("Properties")
                        .HasForeignKey("ConstructorStepPropertyTypeId");

                    b.Navigation("ConstructorStep");

                    b.Navigation("ConstructorStepPropertyGroup");

                    b.Navigation("ConstructorStepPropertyType");
                });

            modelBuilder.Entity("Core.Domain.Entities.Constructor.ConstructorStepPropertyAvailableValue", b =>
                {
                    b.HasOne("Core.Domain.Entities.Constructor.ConstructorStepProperty", "ConstructorStepProperty")
                        .WithMany("AvailableValues")
                        .HasForeignKey("ConstructorStepPropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConstructorStepProperty");
                });

            modelBuilder.Entity("Core.Domain.Entities.Constructor.ConstructorStepPropertyValue", b =>
                {
                    b.HasOne("Core.Domain.Entities.Constructor.ConstructorOrder", "ConstructorOrder")
                        .WithMany("SelectedValues")
                        .HasForeignKey("ConstructorOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Domain.Entities.Constructor.ConstructorStepPropertyAvailableValue", "ConstructorStepPropertyAvailableValue")
                        .WithMany()
                        .HasForeignKey("ConstructorStepPropertyAvailableValueId");

                    b.HasOne("Core.Domain.Entities.Constructor.ConstructorStepProperty", "ConstructorStepProperty")
                        .WithMany("SelectedValues")
                        .HasForeignKey("ConstructorStepPropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConstructorOrder");

                    b.Navigation("ConstructorStepProperty");

                    b.Navigation("ConstructorStepPropertyAvailableValue");
                });

            modelBuilder.Entity("Core.Domain.Entities.Shop.Category", b =>
                {
                    b.HasOne("Core.Domain.Entities.Shop.Category", "ParentCategory")
                        .WithMany("ChildCategories")
                        .HasForeignKey("ParentCategoryId");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("Core.Domain.Entities.Shop.ShopDiscount", b =>
                {
                    b.HasOne("Core.Domain.Entities.Shop.ShopDiscountType", "ShopDiscountType")
                        .WithMany("Discounts")
                        .HasForeignKey("ShopDiscountTypeId");

                    b.Navigation("ShopDiscountType");
                });

            modelBuilder.Entity("Core.Domain.Entities.Shop.ShopOrder", b =>
                {
                    b.HasOne("Core.Domain.Entities.Shop.ShopDelivery", "ShopDelivery")
                        .WithMany("Orders")
                        .HasForeignKey("ShopDeliveryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Core.Domain.Entities.Shop.ShopDiscount", "ShopDiscount")
                        .WithMany("Orders")
                        .HasForeignKey("ShopDiscountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Core.Domain.Entities.Shop.ShopOrderStatus", "ShopOrderStatus")
                        .WithMany("Orders")
                        .HasForeignKey("ShopOrderStatusId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ShopDelivery");

                    b.Navigation("ShopDiscount");

                    b.Navigation("ShopOrderStatus");
                });

            modelBuilder.Entity("Core.Domain.Entities.Shop.ShopOrderItem", b =>
                {
                    b.HasOne("Core.Domain.Entities.Shop.ShopOrder", "ShopOrder")
                        .WithMany("OrderItems")
                        .HasForeignKey("ShopOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Domain.Entities.Shop.ShopProduct", "ShopProduct")
                        .WithMany("OrderItems")
                        .HasForeignKey("ShopProductId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ShopOrder");

                    b.Navigation("ShopProduct");
                });

            modelBuilder.Entity("Core.Domain.Entities.Shop.ShopOrderItemOption", b =>
                {
                    b.HasOne("Core.Domain.Entities.Shop.ShopOrderItem", "ShopOrderItem")
                        .WithMany("SelectedOptions")
                        .HasForeignKey("ShopOrderItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShopOrderItem");
                });

            modelBuilder.Entity("Core.Domain.Entities.Shop.ShopPayment", b =>
                {
                    b.HasOne("Core.Domain.Entities.Shop.ShopOrder", "ShopOrder")
                        .WithMany("Payments")
                        .HasForeignKey("ShopOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Domain.Entities.Shop.ShopPaymentType", "ShopPaymentType")
                        .WithMany("Payments")
                        .HasForeignKey("ShopPaymentTypeId");

                    b.Navigation("ShopOrder");

                    b.Navigation("ShopPaymentType");
                });

            modelBuilder.Entity("Core.Domain.Entities.Shop.ShopProduct", b =>
                {
                    b.HasOne("Core.Domain.Entities.Shop.ShopProductVendor", "ShopProductVendor")
                        .WithMany("Products")
                        .HasForeignKey("ShopProductVendorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ShopProductVendor");
                });

            modelBuilder.Entity("Core.Domain.Entities.Shop.ShopProductCategory", b =>
                {
                    b.HasOne("Core.Domain.Entities.Shop.Category", "Category")
                        .WithMany("ProductCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Domain.Entities.Shop.ShopProduct", "ShopProduct")
                        .WithMany("ProductCategories")
                        .HasForeignKey("ShopProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("ShopProduct");
                });

            modelBuilder.Entity("Core.Domain.Entities.Shop.ShopProductOption", b =>
                {
                    b.HasOne("Core.Domain.Entities.Shop.ShopProduct", "ShopProduct")
                        .WithMany("Options")
                        .HasForeignKey("ShopProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShopProduct");
                });

            modelBuilder.Entity("Core.Domain.Entities.Shop.ShopProductOptionItem", b =>
                {
                    b.HasOne("Core.Domain.Entities.Shop.ShopProductOption", "ShopProductOption")
                        .WithMany("OptionItems")
                        .HasForeignKey("ShopProductOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShopProductOption");
                });

            modelBuilder.Entity("Core.Domain.Entities.Shop.ShopProductPhoto", b =>
                {
                    b.HasOne("Core.Domain.Entities.Shop.ShopProduct", "ShopProduct")
                        .WithMany("Photos")
                        .HasForeignKey("ShopProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShopProduct");
                });

            modelBuilder.Entity("Core.Domain.Entities.Shop.ShopProductProperty", b =>
                {
                    b.HasOne("Core.Domain.Entities.Shop.ShopProductPropertyGroup", "ShopProductPropertyGroup")
                        .WithMany("Properties")
                        .HasForeignKey("ShopProductPropertyGroupId");

                    b.Navigation("ShopProductPropertyGroup");
                });

            modelBuilder.Entity("Core.Domain.Entities.Shop.ShopProductPropertyValue", b =>
                {
                    b.HasOne("Core.Domain.Entities.Shop.ShopProduct", "ShopProduct")
                        .WithMany("PropertyValues")
                        .HasForeignKey("ShopProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Domain.Entities.Shop.ShopProductProperty", "ShopProductProperty")
                        .WithMany("PropertyValues")
                        .HasForeignKey("ShopProductPropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShopProduct");

                    b.Navigation("ShopProductProperty");
                });

            modelBuilder.Entity("ShopProductShopProduct", b =>
                {
                    b.HasOne("Core.Domain.Entities.Shop.ShopProduct", null)
                        .WithMany()
                        .HasForeignKey("RelatedProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Domain.Entities.Shop.ShopProduct", null)
                        .WithMany()
                        .HasForeignKey("ShopProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Domain.Entities.Cms.CmsCategory", b =>
                {
                    b.Navigation("ChildCategories");

                    b.Navigation("NewsItems");

                    b.Navigation("Pages");
                });

            modelBuilder.Entity("Core.Domain.Entities.Cms.CmsComment", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("Core.Domain.Entities.Cms.CmsMenu", b =>
                {
                    b.Navigation("MenuItems");
                });

            modelBuilder.Entity("Core.Domain.Entities.Cms.CmsMenuItem", b =>
                {
                    b.Navigation("ChildMenuItems");
                });

            modelBuilder.Entity("Core.Domain.Entities.Cms.CmsNewsItem", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("Core.Domain.Entities.Cms.CmsPage", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("MenuItems");
                });

            modelBuilder.Entity("Core.Domain.Entities.Cms.CmsPhotoGallery", b =>
                {
                    b.Navigation("NewsItems");

                    b.Navigation("Pages");

                    b.Navigation("Photos");
                });

            modelBuilder.Entity("Core.Domain.Entities.Constructor.ConstructorOrder", b =>
                {
                    b.Navigation("SelectedValues");
                });

            modelBuilder.Entity("Core.Domain.Entities.Constructor.ConstructorStep", b =>
                {
                    b.Navigation("Properties");
                });

            modelBuilder.Entity("Core.Domain.Entities.Constructor.ConstructorStepProperty", b =>
                {
                    b.Navigation("AvailableValues");

                    b.Navigation("SelectedValues");
                });

            modelBuilder.Entity("Core.Domain.Entities.Constructor.ConstructorStepPropertyGroup", b =>
                {
                    b.Navigation("Properties");
                });

            modelBuilder.Entity("Core.Domain.Entities.Constructor.ConstructorStepPropertyType", b =>
                {
                    b.Navigation("Properties");
                });

            modelBuilder.Entity("Core.Domain.Entities.Shop.Category", b =>
                {
                    b.Navigation("ChildCategories");

                    b.Navigation("ProductCategories");
                });

            modelBuilder.Entity("Core.Domain.Entities.Shop.ShopDelivery", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Core.Domain.Entities.Shop.ShopDiscount", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Core.Domain.Entities.Shop.ShopDiscountType", b =>
                {
                    b.Navigation("Discounts");
                });

            modelBuilder.Entity("Core.Domain.Entities.Shop.ShopOrder", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Core.Domain.Entities.Shop.ShopOrderItem", b =>
                {
                    b.Navigation("SelectedOptions");
                });

            modelBuilder.Entity("Core.Domain.Entities.Shop.ShopOrderStatus", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Core.Domain.Entities.Shop.ShopPaymentType", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Core.Domain.Entities.Shop.ShopProduct", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Options");

                    b.Navigation("OrderItems");

                    b.Navigation("Photos");

                    b.Navigation("ProductCategories");

                    b.Navigation("PropertyValues");
                });

            modelBuilder.Entity("Core.Domain.Entities.Shop.ShopProductOption", b =>
                {
                    b.Navigation("OptionItems");
                });

            modelBuilder.Entity("Core.Domain.Entities.Shop.ShopProductProperty", b =>
                {
                    b.Navigation("PropertyValues");
                });

            modelBuilder.Entity("Core.Domain.Entities.Shop.ShopProductPropertyGroup", b =>
                {
                    b.Navigation("Properties");
                });

            modelBuilder.Entity("Core.Domain.Entities.Shop.ShopProductVendor", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
